// Generated by Phaser Editor v1.4.0 (Phaser v2.6.2)


/**
 * stae.
 */
function stae() {
	
	Phaser.State.call(this);
	
}

/** @type Phaser.State */
var stae_proto = Object.create(Phaser.State.prototype);
stae.prototype = stae_proto;
stae.prototype.constructor = stae;

stae.prototype.init = function () {
	
};

stae.prototype.preload = function () {
	
};

stae.prototype.create = function () {
	
};

/* --- end generated code --- */
// -- user code here --
